### PR TITLE
update cosign after testing build privately

### PR DESCRIPTION
**Pull request by Sarahtonein**

### CODE REVIEW

**Comment by Balugrizzly** [comment]
Should this be merged?
I just merged "build_failure"

**Comment by Balugrizzly** [comment]
If not then what is this?

**Comment by Sarahtonein** [comment]
> Should this be merged? I just merged "build_failure"

I think what you merged with the build failure was the pk-go-dev branch which was still using the previous cosign version. This PR contains the updated version

**Review by Balugrizzly — APPROVED** [review]
A

**Pull request merged**
