### PR TITLE
Player json example to operate and iterate off of

### PR DESCRIPTION
**Pull request by laprasdev**
Just adding json to form consensus around for models

### CODE REVIEW

**Comment by laprasdev** [comment]
https://github.com/BloomGameStudio/PlayerService/issues/34

**Comment by Balugrizzly** [comment]
@laprasdev does this replace the master json in the issue?
hows that relation to that?

**Comment by laprasdev** [comment]
@Balugrizzly yes it does. This makes it part of the project, we can close the issue, and as we evolve the data model(s) we will do it through prs to this json, is how I look at it

**Comment by Balugrizzly** [comment]
Sounds good

**Review by Balugrizzly — APPROVED** [review]

**Pull request merged**
