### PR TITLE
Add scale socket

### PR DESCRIPTION
**Pull request by bagelface**
So I admittedly took a sort of "cargo cult" approach to adding this endpoint, since there didn't seem to be anything too different from the position and rotation endpoints. I did add a new variable to Viper config for the websocket timeout time since the same value seemed to be getting used a lot of places as a "magic number".

I'm also not sure how to verify that everything is working correctly. I did some manual testing and it seemed ok, but I think it would be great to start getting a small test suite set up and some point in the near future. I did remote a lot of the debug statements from the reader/writer, but I can add those in if we think they're helpful for the time being while we're still doing primarily manual testing.

### CODE REVIEW

**Comment by Balugrizzly** [comment]
@bagelface appreciate the contribution 
can you resolve merge conflicts?

**Comment by Balugrizzly** [comment]
> So I admittedly took a sort of "cargo cult" approach to adding this endpoint, since there didn't seem to be anything too different from the position and rotation endpoints. I did add a new variable to Viper config for the websocket timeout time since the same value seemed to be getting used a lot of places as a "magic number".
> 
> I'm also not sure how to verify that everything is working correctly. I did some manual testing and it seemed ok, but I think it would be great to start getting a small test suite set up and some point in the near future. I did remote a lot of the debug statements from the reader/writer, but I can add those in if we think they're helpful for the time being while we're still doing primarily manual testing.

Not sure what you mean by cargo cult
Are you talking about those island villagers that pray to planes? If so i still dont know what you mean :)

As for testing there is already a ticket to add testing so you are more than welcome to add that.

**Comment by Balugrizzly** [comment]
Overall Looks good 
will merge after you resolved merge conflicts

**Comment by bagelface** [comment]
> > So I admittedly took a sort of "cargo cult" approach to adding this endpoint, since there didn't seem to be anything too different from the position and rotation endpoints. I did add a new variable to Viper config for the websocket timeout time since the same value seemed to be getting used a lot of places as a "magic number".
> > I'm also not sure how to verify that everything is working correctly. I did some manual testing and it seemed ok, but I think it would be great to start getting a small test suite set up and some point in the near future. I did remote a lot of the debug statements from the reader/writer, but I can add those in if we think they're helpful for the time being while we're still doing primarily manual testing.
> 
> Not sure what you mean by cargo cult Are you talking about those island villagers that pray to planes? If so i still dont know what you mean :)
> 
> As for testing there is already a ticket to add testing so you are more than welcome to add that.

Haha it was an term an old PM of mine used to use when people would just copy and paste other people's code without really scrutinizing it for your usage. Not sure how widely know the term is.

Merge conflicts resolved

**Pull request merged**
