### PR TITLE
update cosign-release version

### PR DESCRIPTION
**Pull request by Sarahtonein**
Updated .github\workflows cosign-release to version v1.11.1

### CODE REVIEW

**Comment by Balugrizzly** [comment]
This fixes build failures?

**Comment by Sarahtonein** [comment]
> This fixes build failures?

I am not so sure, is there a way to test this locally? 

I thought based off the error in the workflow related to the version that updating it would resolve the problem.

```
Run sigstore/cosign-installer@f3c664df7af40[9](https://github.com/BloomGameStudio/PlayerService/actions/runs/6903534213/job/18782410159#step:3:10)cb4873aa5068053ba9d61a57b6
Run #!/bin/bash
INFO: Downloading bootstrap version 'v1.11.1' of cosign to verify version to be installed...
      https://storage.googleapis.com/cosign-releases/v1.11.1/cosign-linux-amd64
ERROR: Unable to validate cosign version: 'v1.11.0'
Error: Process completed with exit code 1.
```

**Comment by Balugrizzly** [comment]
Making prs that hopefully fix issues hahah :) i must be rubbing off of you 
create a private branch or smthing private and see

**Comment by Balugrizzly** [comment]
Deleting as it was closed

**Pull request closed without merging**
